new feature: crop to selection
david-fletcher/super-export pull request #2
Opened 2022-02-12 23:05 UTC by beetrootpaul

In this PR I implemented a "Crop to selection" feature. Example use case: canvas contain multiple version of some logo, and you want to marquee one of them and export as a PNG upscaled a lot.

I organised my changes into kinda isolated commits. Take a look at them and their messages in order to have better understanding of what has happened in this PR.

2022-02-12 23:39 UTC, david-fletcher requested changes
This looks great! If you don't mind adding some parentheses in that one function, I'll merge this PR in and then get the release prepared! Thanks again for doing this!

2022-02-12 23:39 UTC, david-fletcher commented on extension/super-export.lua
> +        width = original_width * resize_percentage / 100,
would you mind adding the parentheses back in here to indicate order of operations?
![image](https://user-images.githubusercontent.com/25467793/153732176-f424eeb0-f370-46fe-91ea-abcf7822aa94.png)

2022-02-12 23:58 UTC, beetrootpaul commented on extension/super-export.lua
> +        width = original_width * resize_percentage / 100,
no problem 👍 BTW Why does this matter? I mean, I even learnt in the past (but in another programming language with different data type for numbers, I suppose) to multiple first, then divide, not the other way 🤔 

(commit in preparation)

2022-02-12 23:59 UTC, beetrootpaul commented on extension/super-export.lua
> +        width = original_width * resize_percentage / 100,
added in https://github.com/david-fletcher/super-export/pull/2/commits/0b3a3b7e02b0aa61486c0b6894ac28a21b052a63

2022-02-13 01:28 UTC, david-fletcher approved these changes
great work!

2022-02-13 01:29 UTC, merged